# This workflows will create a standalone executable for mac os 11.

name: Create Standalone (mac OS 11)

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-11.0

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Create executable
      run: |
        python -m venv .venv
        . .venv/bin/activate
        python -m pip install --upgrade pip
        pip install .
        pip install pyinstaller doit pillow
        doit prepare_build
        pyinstaller pyinstaller.spec --onefile
        ls dist
        cd dist
        ls -l ./mad_gui
        sudo chmod +x ./mad_gui
        ls -l ./mad_gui
        sudo tar -czf mad_gui.tgz mad_gui
        ls
        
    - uses: actions/upload-artifact@v2
      with:
        name: mac_11_executable
        path: /Users/runner/work/mad-gui/mad-gui/dist/

