# This workflows will create a standalone executable for Ubuntu.

name: Create Standalone (Ubuntu)

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        sudo apt-get update
        python -m pip install --upgrade pip
        pip install poetry
        sudo apt-get autoclean
        sudo apt-get install -y --no-install-recommends qtbase5-dev-tools xvfb libegl1-mesa x11-xserver-utils libxkbcommon-x11-0 x11-utils
        sudo apt-get clean
        sudo apt-get purge -y build-essential
        sudo apt-get purge -y cmake
        sudo apt-get install -y build-essential libgl1-mesa-dev
        sudo apt-get install -y libxcb-xinerama0
        sudo apt-get install -y libpulse-dev
        sudo apt-get install -y tk
        sudo apt-get install -y libqt5gstreamer-dev
        sudo apt-get install -y libgssapi-krb5-2
        sudo apt-get install -y libqt5multimedia5-plugins
        sudo add-apt-repository universe
        sudo apt-get install libgstreamer1.0-dev libgstreamer-plugins-bad1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-good1.0-dev
        sudo apt-get -y install git
        sudo apt-get -y install libpulse-mainloop-glib0
    - name: Create executable
      run: |
        python -m venv .venv
        . .venv/bin/activate
        python -m pip install --upgrade pip
        pip install .
        pip install pyinstaller doit pillow
        doit prepare_build
        pyinstaller pyinstaller.spec
        ls dist
        
      
    - uses: actions/upload-artifact@v3
      with:
        name: ubuntu_executable
        path: /home/runner/work/mad-gui/mad-gui/dist/mad_gui
        


