# This workflows will create a standalone executable for windows.

name: Create Standalone (Windows)

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Create executable
      run: |
        python -m venv .venv
        .venv/Scripts/activate
        python -m pip install --upgrade pip
        pip install .
        pip install pyinstaller doit pillow
        doit prepare_build
        pyinstaller pyinstaller.spec --onefile
        ls dist
        
    - uses: actions/upload-artifact@v2
      with:
        name: windows_executable
        path: D:\a\mad-gui\mad-gui\dist\
        
